# Generated by Django 4.1.3 on 2022-11-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Kids', 'Kids'), ('Mystery', 'Mystery'), ('Fiction', 'Fiction'), ('Sci-Fi', 'Sci-Fi'), ('Fantasy', 'Fantasy'), ('Nonfiction', 'Nonfiction'), ('History', 'History'), ('Thriller', 'Thriller')], default='Nonfiction', max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='private',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='status',
            field=models.CharField(choices=[('Want-to-read', 'Want-to-read'), ('No Status', 'No Status'), ('Reading', 'Reading'), ('Read/Done', 'Read/Done')], default='No Status', max_length=50),
        ),
    ]
