# Generated by Django 4.1.3 on 2022-11-14 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Kids', 'Kids'), ('Thriller', 'Thriller'), ('Fiction', 'Fiction'), ('Mystery', 'Mystery'), ('Nonfiction', 'Nonfiction'), ('History', 'History'), ('Sci-Fi', 'Sci-Fi')], default='Nonfiction', max_length=50),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='status',
            field=models.CharField(choices=[('Read/Done', 'Read/Done'), ('Reading', 'Reading'), ('Want-to-read', 'Want-to-read'), ('No Status', 'No Status')], default='No Status', max_length=50),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, max_length=4000, null=True)),
                ('private', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Private', max_length=20)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
