# Generated by Django 4.1.3 on 2022-11-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0002_alter_book_genre_alter_tracker_status_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Nonfiction', 'Nonfiction'), ('Mystery', 'Mystery'), ('Kids', 'Kids'), ('Fantasy', 'Fantasy'), ('History', 'History'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller'), ('Fiction', 'Fiction')], default='Nonfiction', max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='private',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='status',
            field=models.CharField(choices=[('Want-to-read', 'Want-to-read'), ('No Status', 'No Status'), ('Read/Done', 'Read/Done'), ('Reading', 'Reading')], default='No Status', max_length=50),
        ),
    ]
